[tool.poetry]
name = "TellMe"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.7"
parse = "^1.18.0"
asyncio_extras = "^1.3.2"
py-ulid = "^1.0.3"
tensorflow = "^2.4.0"
youtube_dl = "^2021.1.8"
"discord.py[voice]" = {git = "https://github.com/Gorialis/discord.py", rev = "voice-recv-mk3"}
SpeechRecognition = "^3.8.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
