[tool.poetry]
name = "TellMe"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "~3.7 || ~3.8"
parse = "^1.18.0"
py-ulid = "^1.0.3"
tensorflow = "2.2.0"
youtube_dl = "^2021.1.8"
"discord.py" = {git = "https://github.com/Gorialis/discord.py", rev = "voice-recv-mk3"}
SpeechRecognition = "^3.8.1"
Keras = "2.3.1"
deepsegment = "^2.3.1"
rake-nltk = "^1.0.4"
pyttsx3 = "^2.90"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
